mutation {
    addTask(
        title: "Reboot styling",
        weight: 2,
        description: "Add Bootstrap to reset the CSS styling."
    ) {
        title
        weight
        description
    }
}
